import pytest
from server import app

@pytest.fixture
def client():
    """Fixture to set up Flask test client"""
    with app.test_client() as client:
        yield client

def test_jwks(client):
    """Test the /jwks endpoint"""
    response = client.get('/jwks')
    assert response.status_code == 200
    data = response.get_json()
    assert "keys" in data

def test_auth_valid(client):
    """Test the /auth endpoint for a valid JWT"""
    # key is generated by calling /jwks
    jwks_response = client.get('/jwks')  
    print("JWKS response status:", jwks_response.status_code)  
    print("JWKS response data:", jwks_response.get_json())  
    
    # testing the /auth endpoint
    response = client.post('/auth')
    print("Auth response status:", response.status_code)  
    print("Auth response data:", response.get_json())  
    assert response.status_code == 200
    data = response.get_json()
    assert "token" in data



def test_auth_expired(client):
    """Test the /auth endpoint for an expired JWT"""
    response = client.post('/auth?expired=true')
    assert response.status_code == 200 or response.status_code == 400
    data = response.get_json()
    if response.status_code == 200:
        assert "token" in data
    else:
        assert "error" in data
